language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
install:
  - mvn clean install -Dmaven.test.skip=true
script:
  - mvn test
after_success:
  - mvn test jacoco:report coveralls:report
notifications:
  email:
    - heyuxian.me@gmail.com